import type { CartItem } from "../context/cart-context";
import { Tags } from "../pages/home/components/card";

export const Cards: CartItem[] = [
  {
    id: 1,
    title: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: "9.90",
    src: "src/assets/Type=Expresso.png",
    tag: [Tags.TRADICIONAL],
  },
  {
    id: 2,
    title: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: "9.90",
    src: "src/assets/Type=Americano.png",
    tag: [Tags.TRADICIONAL],
  },
  {
    id: 3,
    title: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: "9.90",
    src: "src/assets/Type=Expresso Cremoso.png",
    tag: [Tags.TRADICIONAL],
  },
  {
    id: 4,
    title: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: "9.90",
    src: "src/assets/Type=Café Gelado.png",
    tag: [Tags.TRADICIONAL, Tags.GELADO],
  },
  {
    id: 5,
    title: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: "9.90",
    src: "src/assets/Type=Café com Leite.png",
    tag: [Tags.TRADICIONAL, Tags.COM_LEITE],
  },
  {
    id: 6,
    title: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: "9.90",
    src: "src/assets/Type=Latte.png",
    tag: [Tags.TRADICIONAL, Tags.COM_LEITE],
  },
  {
    id: 7,
    title: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: "9.90",
    src: "src/assets/Type=Capuccino.png",
    tag: [Tags.TRADICIONAL, Tags.COM_LEITE],
  },
  {
    id: 8,
    title: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: "9.90",
    src: "src/assets/Type=Macchiato.png",
    tag: [Tags.TRADICIONAL, Tags.COM_LEITE],
  },
  {
    id: 9,
    title: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: "9.90",
    src: "src/assets/Type=Mochaccino.png",
    tag: [Tags.TRADICIONAL, Tags.COM_LEITE],
  },
  {
    id: 10,
    title: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: "9.90",
    src: "src/assets/Type=Chocolate Quente.png",
    tag: [Tags.ESPECIAL, Tags.COM_LEITE],
  },
  {
    id: 11,
    title: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: "9.90",
    src: "src/assets/Type=Cubano.png",
    tag: [Tags.ESPECIAL, Tags.ALCOÓLICO, Tags.GELADO],
  },
  {
    id: 12,
    title: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: "9.90",
    src: "src/assets/Type=Havaiano.png",
    tag: [Tags.ESPECIAL],
  },
  {
    id: 13,
    title: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: "9.90",
    src: "src/assets/arabe.png",
    tag: [Tags.ESPECIAL],
  },
  {
    id: 14,
    title: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: "9.90",
    src: "src/assets/Type=Irlandês.png",
    tag: [Tags.ESPECIAL, Tags.ALCOÓLICO],
  },
];
